name: Tour Weather Cron

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-weather-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests firebase-admin

      - name: Run Weather Check Script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python check_weather.py
        
